package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsCategory;
import cn.hd.ws.dao.EcsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int countByExample(EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int deleteByExample(EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int deleteByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int insert(EcsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int insertSelective(EcsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    List<EcsCategory> selectByExample(EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    EcsCategory selectByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsCategory record, @Param("example") EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int updateByExample(@Param("record") EcsCategory record, @Param("example") EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int updateByPrimaryKeySelective(EcsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    int updateByPrimaryKey(EcsCategory record);
}