package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsGoodsActivity;
import cn.hd.ws.dao.EcsGoodsActivityExample;
import cn.hd.ws.dao.EcsGoodsActivityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsGoodsActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int countByExample(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int deleteByExample(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int deleteByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int insert(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int insertSelective(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    List<EcsGoodsActivityWithBLOBs> selectByExampleWithBLOBs(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    List<EcsGoodsActivity> selectByExample(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    EcsGoodsActivityWithBLOBs selectByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsGoodsActivityWithBLOBs record, @Param("example") EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") EcsGoodsActivityWithBLOBs record, @Param("example") EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int updateByExample(@Param("record") EcsGoodsActivity record, @Param("example") EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int updateByPrimaryKeySelective(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    int updateByPrimaryKey(EcsGoodsActivity record);
}