package cn.hd.ws.dao;

import java.math.BigDecimal;

public class EcsGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.cat_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Short catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_sn
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_name
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_name_style
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsNameStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.click_count
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer clickCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.brand_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Short brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.provider_name
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String providerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_number
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Short goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_weight
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private BigDecimal goodsWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.market_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.shop_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private BigDecimal shopPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.promote_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private BigDecimal promotePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.promote_start_date
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer promoteStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.promote_end_date
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer promoteEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.warn_number
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Byte warnNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.keywords
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_brief
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsBrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_thumb
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_img
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.original_img
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String originalImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_real
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Byte isReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.extension_code
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_on_sale
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isOnSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_alone_sale
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isAloneSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_shipping
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isShipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.add_time
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.sort_order
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Short sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_delete
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_best
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isBest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_new
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_hot
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_promote
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isPromote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.bonus_type_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Byte bonusTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.last_update
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_type
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Short goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.seller_note
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String sellerNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.give_integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer giveIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.rank_integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Integer rankIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.suppliers_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Short suppliersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_check
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private Boolean isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_desc
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    private String goodsDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_id
     *
     * @return the value of ecs_goods.goods_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_id
     *
     * @param goodsId the value for ecs_goods.goods_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.cat_id
     *
     * @return the value of ecs_goods.cat_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Short getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.cat_id
     *
     * @param catId the value for ecs_goods.cat_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setCatId(Short catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_sn
     *
     * @return the value of ecs_goods.goods_sn
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_sn
     *
     * @param goodsSn the value for ecs_goods.goods_sn
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_name
     *
     * @return the value of ecs_goods.goods_name
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_name
     *
     * @param goodsName the value for ecs_goods.goods_name
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_name_style
     *
     * @return the value of ecs_goods.goods_name_style
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsNameStyle() {
        return goodsNameStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_name_style
     *
     * @param goodsNameStyle the value for ecs_goods.goods_name_style
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsNameStyle(String goodsNameStyle) {
        this.goodsNameStyle = goodsNameStyle == null ? null : goodsNameStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.click_count
     *
     * @return the value of ecs_goods.click_count
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.click_count
     *
     * @param clickCount the value for ecs_goods.click_count
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.brand_id
     *
     * @return the value of ecs_goods.brand_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Short getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.brand_id
     *
     * @param brandId the value for ecs_goods.brand_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setBrandId(Short brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.provider_name
     *
     * @return the value of ecs_goods.provider_name
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.provider_name
     *
     * @param providerName the value for ecs_goods.provider_name
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setProviderName(String providerName) {
        this.providerName = providerName == null ? null : providerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_number
     *
     * @return the value of ecs_goods.goods_number
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_number
     *
     * @param goodsNumber the value for ecs_goods.goods_number
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_weight
     *
     * @return the value of ecs_goods.goods_weight
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public BigDecimal getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_weight
     *
     * @param goodsWeight the value for ecs_goods.goods_weight
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsWeight(BigDecimal goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.market_price
     *
     * @return the value of ecs_goods.market_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.market_price
     *
     * @param marketPrice the value for ecs_goods.market_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.shop_price
     *
     * @return the value of ecs_goods.shop_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public BigDecimal getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.shop_price
     *
     * @param shopPrice the value for ecs_goods.shop_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setShopPrice(BigDecimal shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.promote_price
     *
     * @return the value of ecs_goods.promote_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public BigDecimal getPromotePrice() {
        return promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.promote_price
     *
     * @param promotePrice the value for ecs_goods.promote_price
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setPromotePrice(BigDecimal promotePrice) {
        this.promotePrice = promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.promote_start_date
     *
     * @return the value of ecs_goods.promote_start_date
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getPromoteStartDate() {
        return promoteStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.promote_start_date
     *
     * @param promoteStartDate the value for ecs_goods.promote_start_date
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setPromoteStartDate(Integer promoteStartDate) {
        this.promoteStartDate = promoteStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.promote_end_date
     *
     * @return the value of ecs_goods.promote_end_date
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getPromoteEndDate() {
        return promoteEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.promote_end_date
     *
     * @param promoteEndDate the value for ecs_goods.promote_end_date
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setPromoteEndDate(Integer promoteEndDate) {
        this.promoteEndDate = promoteEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.warn_number
     *
     * @return the value of ecs_goods.warn_number
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Byte getWarnNumber() {
        return warnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.warn_number
     *
     * @param warnNumber the value for ecs_goods.warn_number
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setWarnNumber(Byte warnNumber) {
        this.warnNumber = warnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.keywords
     *
     * @return the value of ecs_goods.keywords
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.keywords
     *
     * @param keywords the value for ecs_goods.keywords
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_brief
     *
     * @return the value of ecs_goods.goods_brief
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsBrief() {
        return goodsBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_brief
     *
     * @param goodsBrief the value for ecs_goods.goods_brief
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsBrief(String goodsBrief) {
        this.goodsBrief = goodsBrief == null ? null : goodsBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_thumb
     *
     * @return the value of ecs_goods.goods_thumb
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsThumb() {
        return goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_thumb
     *
     * @param goodsThumb the value for ecs_goods.goods_thumb
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsThumb(String goodsThumb) {
        this.goodsThumb = goodsThumb == null ? null : goodsThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_img
     *
     * @return the value of ecs_goods.goods_img
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_img
     *
     * @param goodsImg the value for ecs_goods.goods_img
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.original_img
     *
     * @return the value of ecs_goods.original_img
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getOriginalImg() {
        return originalImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.original_img
     *
     * @param originalImg the value for ecs_goods.original_img
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setOriginalImg(String originalImg) {
        this.originalImg = originalImg == null ? null : originalImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_real
     *
     * @return the value of ecs_goods.is_real
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Byte getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_real
     *
     * @param isReal the value for ecs_goods.is_real
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsReal(Byte isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.extension_code
     *
     * @return the value of ecs_goods.extension_code
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.extension_code
     *
     * @param extensionCode the value for ecs_goods.extension_code
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_on_sale
     *
     * @return the value of ecs_goods.is_on_sale
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_on_sale
     *
     * @param isOnSale the value for ecs_goods.is_on_sale
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_alone_sale
     *
     * @return the value of ecs_goods.is_alone_sale
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsAloneSale() {
        return isAloneSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_alone_sale
     *
     * @param isAloneSale the value for ecs_goods.is_alone_sale
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsAloneSale(Boolean isAloneSale) {
        this.isAloneSale = isAloneSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_shipping
     *
     * @return the value of ecs_goods.is_shipping
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsShipping() {
        return isShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_shipping
     *
     * @param isShipping the value for ecs_goods.is_shipping
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsShipping(Boolean isShipping) {
        this.isShipping = isShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.integral
     *
     * @return the value of ecs_goods.integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.integral
     *
     * @param integral the value for ecs_goods.integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.add_time
     *
     * @return the value of ecs_goods.add_time
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.add_time
     *
     * @param addTime the value for ecs_goods.add_time
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.sort_order
     *
     * @return the value of ecs_goods.sort_order
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Short getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.sort_order
     *
     * @param sortOrder the value for ecs_goods.sort_order
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_delete
     *
     * @return the value of ecs_goods.is_delete
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_delete
     *
     * @param isDelete the value for ecs_goods.is_delete
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_best
     *
     * @return the value of ecs_goods.is_best
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsBest() {
        return isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_best
     *
     * @param isBest the value for ecs_goods.is_best
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsBest(Boolean isBest) {
        this.isBest = isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_new
     *
     * @return the value of ecs_goods.is_new
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_new
     *
     * @param isNew the value for ecs_goods.is_new
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_hot
     *
     * @return the value of ecs_goods.is_hot
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_hot
     *
     * @param isHot the value for ecs_goods.is_hot
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_promote
     *
     * @return the value of ecs_goods.is_promote
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsPromote() {
        return isPromote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_promote
     *
     * @param isPromote the value for ecs_goods.is_promote
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsPromote(Boolean isPromote) {
        this.isPromote = isPromote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.bonus_type_id
     *
     * @return the value of ecs_goods.bonus_type_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Byte getBonusTypeId() {
        return bonusTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.bonus_type_id
     *
     * @param bonusTypeId the value for ecs_goods.bonus_type_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setBonusTypeId(Byte bonusTypeId) {
        this.bonusTypeId = bonusTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.last_update
     *
     * @return the value of ecs_goods.last_update
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.last_update
     *
     * @param lastUpdate the value for ecs_goods.last_update
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setLastUpdate(Integer lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_type
     *
     * @return the value of ecs_goods.goods_type
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Short getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_type
     *
     * @param goodsType the value for ecs_goods.goods_type
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsType(Short goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.seller_note
     *
     * @return the value of ecs_goods.seller_note
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getSellerNote() {
        return sellerNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.seller_note
     *
     * @param sellerNote the value for ecs_goods.seller_note
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setSellerNote(String sellerNote) {
        this.sellerNote = sellerNote == null ? null : sellerNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.give_integral
     *
     * @return the value of ecs_goods.give_integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getGiveIntegral() {
        return giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.give_integral
     *
     * @param giveIntegral the value for ecs_goods.give_integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGiveIntegral(Integer giveIntegral) {
        this.giveIntegral = giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.rank_integral
     *
     * @return the value of ecs_goods.rank_integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Integer getRankIntegral() {
        return rankIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.rank_integral
     *
     * @param rankIntegral the value for ecs_goods.rank_integral
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setRankIntegral(Integer rankIntegral) {
        this.rankIntegral = rankIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.suppliers_id
     *
     * @return the value of ecs_goods.suppliers_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Short getSuppliersId() {
        return suppliersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.suppliers_id
     *
     * @param suppliersId the value for ecs_goods.suppliers_id
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setSuppliersId(Short suppliersId) {
        this.suppliersId = suppliersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_check
     *
     * @return the value of ecs_goods.is_check
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public Boolean getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_check
     *
     * @param isCheck the value for ecs_goods.is_check
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setIsCheck(Boolean isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_desc
     *
     * @return the value of ecs_goods.goods_desc
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_desc
     *
     * @param goodsDesc the value for ecs_goods.goods_desc
     *
     * @mbggenerated Tue Jun 16 17:31:50 CST 2015
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }
}