package cn.hd.ws.dao;

public class EcsGoodsActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.act_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.act_name
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private String actName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.act_type
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Byte actType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.goods_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.product_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.goods_name
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.start_time
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Integer startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.end_time
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Integer endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.is_finished
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private Byte isFinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.act_cats
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private String actCats;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.act_id
     *
     * @return the value of ecs_goods_activity.act_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.act_id
     *
     * @param actId the value for ecs_goods_activity.act_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.act_name
     *
     * @return the value of ecs_goods_activity.act_name
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.act_name
     *
     * @param actName the value for ecs_goods_activity.act_name
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setActName(String actName) {
        this.actName = actName == null ? null : actName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.act_type
     *
     * @return the value of ecs_goods_activity.act_type
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Byte getActType() {
        return actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.act_type
     *
     * @param actType the value for ecs_goods_activity.act_type
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setActType(Byte actType) {
        this.actType = actType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.goods_id
     *
     * @return the value of ecs_goods_activity.goods_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.goods_id
     *
     * @param goodsId the value for ecs_goods_activity.goods_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.product_id
     *
     * @return the value of ecs_goods_activity.product_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.product_id
     *
     * @param productId the value for ecs_goods_activity.product_id
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.goods_name
     *
     * @return the value of ecs_goods_activity.goods_name
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.goods_name
     *
     * @param goodsName the value for ecs_goods_activity.goods_name
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.start_time
     *
     * @return the value of ecs_goods_activity.start_time
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.start_time
     *
     * @param startTime the value for ecs_goods_activity.start_time
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.end_time
     *
     * @return the value of ecs_goods_activity.end_time
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.end_time
     *
     * @param endTime the value for ecs_goods_activity.end_time
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.is_finished
     *
     * @return the value of ecs_goods_activity.is_finished
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public Byte getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.is_finished
     *
     * @param isFinished the value for ecs_goods_activity.is_finished
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setIsFinished(Byte isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.act_cats
     *
     * @return the value of ecs_goods_activity.act_cats
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public String getActCats() {
        return actCats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.act_cats
     *
     * @param actCats the value for ecs_goods_activity.act_cats
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setActCats(String actCats) {
        this.actCats = actCats == null ? null : actCats.trim();
    }
}