package cn.hd.ws.dao;

public class EcsGoodsActivityWithBLOBs extends EcsGoodsActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.act_desc
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private String actDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods_activity.ext_info
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    private String extInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.act_desc
     *
     * @return the value of ecs_goods_activity.act_desc
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public String getActDesc() {
        return actDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.act_desc
     *
     * @param actDesc the value for ecs_goods_activity.act_desc
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setActDesc(String actDesc) {
        this.actDesc = actDesc == null ? null : actDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods_activity.ext_info
     *
     * @return the value of ecs_goods_activity.ext_info
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods_activity.ext_info
     *
     * @param extInfo the value for ecs_goods_activity.ext_info
     *
     * @mbggenerated Fri Jul 03 16:32:36 CST 2015
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }
}