package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsGoods;
import cn.hd.ws.dao.EcsGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int countByExample(EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int deleteByExample(EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int insert(EcsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int insertSelective(EcsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    List<EcsGoods> selectByExampleWithBLOBs(EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    List<EcsGoods> selectByExample(EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    EcsGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsGoods record, @Param("example") EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") EcsGoods record, @Param("example") EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int updateByExample(@Param("record") EcsGoods record, @Param("example") EcsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int updateByPrimaryKeySelective(EcsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EcsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods
     *
     * @mbggenerated Thu Jul 23 16:46:46 CST 2015
     */
    int updateByPrimaryKey(EcsGoods record);
}