package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsOrderInfo;
import cn.hd.ws.dao.EcsOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int countByExample(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int deleteByExample(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int insert(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int insertSelective(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    List<EcsOrderInfo> selectByExample(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    EcsOrderInfo selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsOrderInfo record, @Param("example") EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int updateByExample(@Param("record") EcsOrderInfo record, @Param("example") EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int updateByPrimaryKeySelective(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbggenerated Mon Jul 20 10:13:33 CST 2015
     */
    int updateByPrimaryKey(EcsOrderInfo record);
}