package cn.hd.ws.dao;

import java.math.BigDecimal;

public class EcsOrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.order_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.order_sn
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.user_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.order_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Boolean orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.shipping_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Boolean shippingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pay_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Boolean payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.consignee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.country
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Short country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.province
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Short province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.city
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Short city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.district
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Short district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.address
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.zipcode
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.tel
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.mobile
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.email
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.best_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String bestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.sign_building
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String signBuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.postscript
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String postscript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.shipping_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Byte shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.shipping_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String shippingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pay_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Byte payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pay_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.how_oos
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String howOos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.how_surplus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String howSurplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pack_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String packName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.card_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.card_message
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String cardMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.inv_payee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String invPayee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.inv_content
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String invContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.goods_amount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal goodsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.shipping_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal shippingFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.insure_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal insureFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pay_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal payFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pack_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal packFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.card_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal cardFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.money_paid
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal moneyPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.surplus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.integral
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.integral_money
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal integralMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.bonus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal bonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.order_amount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.from_ad
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Short fromAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.referer
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String referer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.add_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.confirm_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer confirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pay_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.shipping_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer shippingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pack_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Byte packId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.card_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Byte cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.bonus_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer bonusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.invoice_no
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.extension_code
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.extension_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer extensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.to_buyer
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String toBuyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.pay_note
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String payNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.agency_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Short agencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.inv_type
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private String invType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.tax
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.is_separate
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Boolean isSeparate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.parent_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_info.discount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    private BigDecimal discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.order_id
     *
     * @return the value of ecs_order_info.order_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.order_id
     *
     * @param orderId the value for ecs_order_info.order_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.order_sn
     *
     * @return the value of ecs_order_info.order_sn
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.order_sn
     *
     * @param orderSn the value for ecs_order_info.order_sn
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.user_id
     *
     * @return the value of ecs_order_info.user_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.user_id
     *
     * @param userId the value for ecs_order_info.user_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.order_status
     *
     * @return the value of ecs_order_info.order_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Boolean getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.order_status
     *
     * @param orderStatus the value for ecs_order_info.order_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.shipping_status
     *
     * @return the value of ecs_order_info.shipping_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Boolean getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.shipping_status
     *
     * @param shippingStatus the value for ecs_order_info.shipping_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setShippingStatus(Boolean shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pay_status
     *
     * @return the value of ecs_order_info.pay_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Boolean getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pay_status
     *
     * @param payStatus the value for ecs_order_info.pay_status
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPayStatus(Boolean payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.consignee
     *
     * @return the value of ecs_order_info.consignee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.consignee
     *
     * @param consignee the value for ecs_order_info.consignee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.country
     *
     * @return the value of ecs_order_info.country
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Short getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.country
     *
     * @param country the value for ecs_order_info.country
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setCountry(Short country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.province
     *
     * @return the value of ecs_order_info.province
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.province
     *
     * @param province the value for ecs_order_info.province
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.city
     *
     * @return the value of ecs_order_info.city
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.city
     *
     * @param city the value for ecs_order_info.city
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.district
     *
     * @return the value of ecs_order_info.district
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Short getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.district
     *
     * @param district the value for ecs_order_info.district
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setDistrict(Short district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.address
     *
     * @return the value of ecs_order_info.address
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.address
     *
     * @param address the value for ecs_order_info.address
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.zipcode
     *
     * @return the value of ecs_order_info.zipcode
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.zipcode
     *
     * @param zipcode the value for ecs_order_info.zipcode
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.tel
     *
     * @return the value of ecs_order_info.tel
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.tel
     *
     * @param tel the value for ecs_order_info.tel
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.mobile
     *
     * @return the value of ecs_order_info.mobile
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.mobile
     *
     * @param mobile the value for ecs_order_info.mobile
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.email
     *
     * @return the value of ecs_order_info.email
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.email
     *
     * @param email the value for ecs_order_info.email
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.best_time
     *
     * @return the value of ecs_order_info.best_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getBestTime() {
        return bestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.best_time
     *
     * @param bestTime the value for ecs_order_info.best_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setBestTime(String bestTime) {
        this.bestTime = bestTime == null ? null : bestTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.sign_building
     *
     * @return the value of ecs_order_info.sign_building
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getSignBuilding() {
        return signBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.sign_building
     *
     * @param signBuilding the value for ecs_order_info.sign_building
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setSignBuilding(String signBuilding) {
        this.signBuilding = signBuilding == null ? null : signBuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.postscript
     *
     * @return the value of ecs_order_info.postscript
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getPostscript() {
        return postscript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.postscript
     *
     * @param postscript the value for ecs_order_info.postscript
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPostscript(String postscript) {
        this.postscript = postscript == null ? null : postscript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.shipping_id
     *
     * @return the value of ecs_order_info.shipping_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Byte getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.shipping_id
     *
     * @param shippingId the value for ecs_order_info.shipping_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setShippingId(Byte shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.shipping_name
     *
     * @return the value of ecs_order_info.shipping_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.shipping_name
     *
     * @param shippingName the value for ecs_order_info.shipping_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pay_id
     *
     * @return the value of ecs_order_info.pay_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Byte getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pay_id
     *
     * @param payId the value for ecs_order_info.pay_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPayId(Byte payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pay_name
     *
     * @return the value of ecs_order_info.pay_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pay_name
     *
     * @param payName the value for ecs_order_info.pay_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.how_oos
     *
     * @return the value of ecs_order_info.how_oos
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getHowOos() {
        return howOos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.how_oos
     *
     * @param howOos the value for ecs_order_info.how_oos
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setHowOos(String howOos) {
        this.howOos = howOos == null ? null : howOos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.how_surplus
     *
     * @return the value of ecs_order_info.how_surplus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getHowSurplus() {
        return howSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.how_surplus
     *
     * @param howSurplus the value for ecs_order_info.how_surplus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setHowSurplus(String howSurplus) {
        this.howSurplus = howSurplus == null ? null : howSurplus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pack_name
     *
     * @return the value of ecs_order_info.pack_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getPackName() {
        return packName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pack_name
     *
     * @param packName the value for ecs_order_info.pack_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPackName(String packName) {
        this.packName = packName == null ? null : packName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.card_name
     *
     * @return the value of ecs_order_info.card_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.card_name
     *
     * @param cardName the value for ecs_order_info.card_name
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.card_message
     *
     * @return the value of ecs_order_info.card_message
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getCardMessage() {
        return cardMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.card_message
     *
     * @param cardMessage the value for ecs_order_info.card_message
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setCardMessage(String cardMessage) {
        this.cardMessage = cardMessage == null ? null : cardMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.inv_payee
     *
     * @return the value of ecs_order_info.inv_payee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getInvPayee() {
        return invPayee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.inv_payee
     *
     * @param invPayee the value for ecs_order_info.inv_payee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setInvPayee(String invPayee) {
        this.invPayee = invPayee == null ? null : invPayee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.inv_content
     *
     * @return the value of ecs_order_info.inv_content
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getInvContent() {
        return invContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.inv_content
     *
     * @param invContent the value for ecs_order_info.inv_content
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setInvContent(String invContent) {
        this.invContent = invContent == null ? null : invContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.goods_amount
     *
     * @return the value of ecs_order_info.goods_amount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.goods_amount
     *
     * @param goodsAmount the value for ecs_order_info.goods_amount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setGoodsAmount(BigDecimal goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.shipping_fee
     *
     * @return the value of ecs_order_info.shipping_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.shipping_fee
     *
     * @param shippingFee the value for ecs_order_info.shipping_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.insure_fee
     *
     * @return the value of ecs_order_info.insure_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getInsureFee() {
        return insureFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.insure_fee
     *
     * @param insureFee the value for ecs_order_info.insure_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setInsureFee(BigDecimal insureFee) {
        this.insureFee = insureFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pay_fee
     *
     * @return the value of ecs_order_info.pay_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pay_fee
     *
     * @param payFee the value for ecs_order_info.pay_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPayFee(BigDecimal payFee) {
        this.payFee = payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pack_fee
     *
     * @return the value of ecs_order_info.pack_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getPackFee() {
        return packFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pack_fee
     *
     * @param packFee the value for ecs_order_info.pack_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPackFee(BigDecimal packFee) {
        this.packFee = packFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.card_fee
     *
     * @return the value of ecs_order_info.card_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getCardFee() {
        return cardFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.card_fee
     *
     * @param cardFee the value for ecs_order_info.card_fee
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setCardFee(BigDecimal cardFee) {
        this.cardFee = cardFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.money_paid
     *
     * @return the value of ecs_order_info.money_paid
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getMoneyPaid() {
        return moneyPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.money_paid
     *
     * @param moneyPaid the value for ecs_order_info.money_paid
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setMoneyPaid(BigDecimal moneyPaid) {
        this.moneyPaid = moneyPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.surplus
     *
     * @return the value of ecs_order_info.surplus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.surplus
     *
     * @param surplus the value for ecs_order_info.surplus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setSurplus(BigDecimal surplus) {
        this.surplus = surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.integral
     *
     * @return the value of ecs_order_info.integral
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.integral
     *
     * @param integral the value for ecs_order_info.integral
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.integral_money
     *
     * @return the value of ecs_order_info.integral_money
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getIntegralMoney() {
        return integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.integral_money
     *
     * @param integralMoney the value for ecs_order_info.integral_money
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setIntegralMoney(BigDecimal integralMoney) {
        this.integralMoney = integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.bonus
     *
     * @return the value of ecs_order_info.bonus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.bonus
     *
     * @param bonus the value for ecs_order_info.bonus
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.order_amount
     *
     * @return the value of ecs_order_info.order_amount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.order_amount
     *
     * @param orderAmount the value for ecs_order_info.order_amount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.from_ad
     *
     * @return the value of ecs_order_info.from_ad
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Short getFromAd() {
        return fromAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.from_ad
     *
     * @param fromAd the value for ecs_order_info.from_ad
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setFromAd(Short fromAd) {
        this.fromAd = fromAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.referer
     *
     * @return the value of ecs_order_info.referer
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.referer
     *
     * @param referer the value for ecs_order_info.referer
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setReferer(String referer) {
        this.referer = referer == null ? null : referer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.add_time
     *
     * @return the value of ecs_order_info.add_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.add_time
     *
     * @param addTime the value for ecs_order_info.add_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.confirm_time
     *
     * @return the value of ecs_order_info.confirm_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.confirm_time
     *
     * @param confirmTime the value for ecs_order_info.confirm_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setConfirmTime(Integer confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pay_time
     *
     * @return the value of ecs_order_info.pay_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pay_time
     *
     * @param payTime the value for ecs_order_info.pay_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.shipping_time
     *
     * @return the value of ecs_order_info.shipping_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.shipping_time
     *
     * @param shippingTime the value for ecs_order_info.shipping_time
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setShippingTime(Integer shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pack_id
     *
     * @return the value of ecs_order_info.pack_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Byte getPackId() {
        return packId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pack_id
     *
     * @param packId the value for ecs_order_info.pack_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPackId(Byte packId) {
        this.packId = packId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.card_id
     *
     * @return the value of ecs_order_info.card_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Byte getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.card_id
     *
     * @param cardId the value for ecs_order_info.card_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setCardId(Byte cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.bonus_id
     *
     * @return the value of ecs_order_info.bonus_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getBonusId() {
        return bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.bonus_id
     *
     * @param bonusId the value for ecs_order_info.bonus_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setBonusId(Integer bonusId) {
        this.bonusId = bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.invoice_no
     *
     * @return the value of ecs_order_info.invoice_no
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.invoice_no
     *
     * @param invoiceNo the value for ecs_order_info.invoice_no
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.extension_code
     *
     * @return the value of ecs_order_info.extension_code
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.extension_code
     *
     * @param extensionCode the value for ecs_order_info.extension_code
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.extension_id
     *
     * @return the value of ecs_order_info.extension_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getExtensionId() {
        return extensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.extension_id
     *
     * @param extensionId the value for ecs_order_info.extension_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setExtensionId(Integer extensionId) {
        this.extensionId = extensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.to_buyer
     *
     * @return the value of ecs_order_info.to_buyer
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getToBuyer() {
        return toBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.to_buyer
     *
     * @param toBuyer the value for ecs_order_info.to_buyer
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setToBuyer(String toBuyer) {
        this.toBuyer = toBuyer == null ? null : toBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.pay_note
     *
     * @return the value of ecs_order_info.pay_note
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getPayNote() {
        return payNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.pay_note
     *
     * @param payNote the value for ecs_order_info.pay_note
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setPayNote(String payNote) {
        this.payNote = payNote == null ? null : payNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.agency_id
     *
     * @return the value of ecs_order_info.agency_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Short getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.agency_id
     *
     * @param agencyId the value for ecs_order_info.agency_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setAgencyId(Short agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.inv_type
     *
     * @return the value of ecs_order_info.inv_type
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public String getInvType() {
        return invType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.inv_type
     *
     * @param invType the value for ecs_order_info.inv_type
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setInvType(String invType) {
        this.invType = invType == null ? null : invType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.tax
     *
     * @return the value of ecs_order_info.tax
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.tax
     *
     * @param tax the value for ecs_order_info.tax
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.is_separate
     *
     * @return the value of ecs_order_info.is_separate
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Boolean getIsSeparate() {
        return isSeparate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.is_separate
     *
     * @param isSeparate the value for ecs_order_info.is_separate
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setIsSeparate(Boolean isSeparate) {
        this.isSeparate = isSeparate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.parent_id
     *
     * @return the value of ecs_order_info.parent_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.parent_id
     *
     * @param parentId the value for ecs_order_info.parent_id
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_info.discount
     *
     * @return the value of ecs_order_info.discount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_info.discount
     *
     * @param discount the value for ecs_order_info.discount
     *
     * @mbggenerated Wed Jul 15 09:06:14 CST 2015
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
}