package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsOrderGoods;
import cn.hd.ws.dao.EcsOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int countByExample(EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int deleteByExample(EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int insert(EcsOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int insertSelective(EcsOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    List<EcsOrderGoods> selectByExampleWithBLOBs(EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    List<EcsOrderGoods> selectByExample(EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    EcsOrderGoods selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsOrderGoods record, @Param("example") EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") EcsOrderGoods record, @Param("example") EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int updateByExample(@Param("record") EcsOrderGoods record, @Param("example") EcsOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int updateByPrimaryKeySelective(EcsOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EcsOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    int updateByPrimaryKey(EcsOrderGoods record);
}