package cn.hd.ws.dao;

import java.math.BigDecimal;

public class EcsOrderGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.rec_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Integer recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.order_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_name
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_sn
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.product_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_number
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Short goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.market_price
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_price
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.send_number
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Short sendNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.is_real
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Boolean isReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.extension_code
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private String extensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.parent_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.is_gift
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private Short isGift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_attr_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private String goodsAttrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order_goods.goods_attr
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    private String goodsAttr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.rec_id
     *
     * @return the value of ecs_order_goods.rec_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.rec_id
     *
     * @param recId the value for ecs_order_goods.rec_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.order_id
     *
     * @return the value of ecs_order_goods.order_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.order_id
     *
     * @param orderId the value for ecs_order_goods.order_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_id
     *
     * @return the value of ecs_order_goods.goods_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_id
     *
     * @param goodsId the value for ecs_order_goods.goods_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_name
     *
     * @return the value of ecs_order_goods.goods_name
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_name
     *
     * @param goodsName the value for ecs_order_goods.goods_name
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_sn
     *
     * @return the value of ecs_order_goods.goods_sn
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_sn
     *
     * @param goodsSn the value for ecs_order_goods.goods_sn
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.product_id
     *
     * @return the value of ecs_order_goods.product_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.product_id
     *
     * @param productId the value for ecs_order_goods.product_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_number
     *
     * @return the value of ecs_order_goods.goods_number
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Short getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_number
     *
     * @param goodsNumber the value for ecs_order_goods.goods_number
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsNumber(Short goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.market_price
     *
     * @return the value of ecs_order_goods.market_price
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.market_price
     *
     * @param marketPrice the value for ecs_order_goods.market_price
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_price
     *
     * @return the value of ecs_order_goods.goods_price
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_price
     *
     * @param goodsPrice the value for ecs_order_goods.goods_price
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.send_number
     *
     * @return the value of ecs_order_goods.send_number
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Short getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.send_number
     *
     * @param sendNumber the value for ecs_order_goods.send_number
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setSendNumber(Short sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.is_real
     *
     * @return the value of ecs_order_goods.is_real
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Boolean getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.is_real
     *
     * @param isReal the value for ecs_order_goods.is_real
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setIsReal(Boolean isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.extension_code
     *
     * @return the value of ecs_order_goods.extension_code
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.extension_code
     *
     * @param extensionCode the value for ecs_order_goods.extension_code
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode == null ? null : extensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.parent_id
     *
     * @return the value of ecs_order_goods.parent_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.parent_id
     *
     * @param parentId the value for ecs_order_goods.parent_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.is_gift
     *
     * @return the value of ecs_order_goods.is_gift
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public Short getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.is_gift
     *
     * @param isGift the value for ecs_order_goods.is_gift
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setIsGift(Short isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_attr_id
     *
     * @return the value of ecs_order_goods.goods_attr_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public String getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_attr_id
     *
     * @param goodsAttrId the value for ecs_order_goods.goods_attr_id
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsAttrId(String goodsAttrId) {
        this.goodsAttrId = goodsAttrId == null ? null : goodsAttrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order_goods.goods_attr
     *
     * @return the value of ecs_order_goods.goods_attr
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order_goods.goods_attr
     *
     * @param goodsAttr the value for ecs_order_goods.goods_attr
     *
     * @mbggenerated Wed Jul 15 08:07:28 CST 2015
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr == null ? null : goodsAttr.trim();
    }
}