package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsRegion;
import cn.hd.ws.dao.EcsRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int countByExample(EcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int deleteByExample(EcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int deleteByPrimaryKey(Short regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int insert(EcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int insertSelective(EcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    List<EcsRegion> selectByExample(EcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    EcsRegion selectByPrimaryKey(Short regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsRegion record, @Param("example") EcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int updateByExample(@Param("record") EcsRegion record, @Param("example") EcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int updateByPrimaryKeySelective(EcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbggenerated Thu Jul 23 11:19:15 CST 2015
     */
    int updateByPrimaryKey(EcsRegion record);
}