package cn.hd.ws.dao;

import cn.hd.ws.dao.EcsUsers;
import cn.hd.ws.dao.EcsUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int countByExample(EcsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int deleteByExample(EcsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int insert(EcsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int insertSelective(EcsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    List<EcsUsers> selectByExample(EcsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    EcsUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") EcsUsers record, @Param("example") EcsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int updateByExample(@Param("record") EcsUsers record, @Param("example") EcsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int updateByPrimaryKeySelective(EcsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_users
     *
     * @mbggenerated Fri Jul 17 11:57:47 CST 2015
     */
    int updateByPrimaryKey(EcsUsers record);
}