package cn.hd.ws.dao;

import java.util.Date;

public class Wxorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.id
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.orderid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.appid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.mchid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String mchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.sign
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.noncestr
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String noncestr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.goodstag
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String goodstag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.accountid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.prepayid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private Integer prepayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.goods
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private String goods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.crdate
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private Date crdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.status
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.id
     *
     * @return the value of wxorder.id
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.id
     *
     * @param id the value for wxorder.id
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.orderid
     *
     * @return the value of wxorder.orderid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.orderid
     *
     * @param orderid the value for wxorder.orderid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.appid
     *
     * @return the value of wxorder.appid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.appid
     *
     * @param appid the value for wxorder.appid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.mchid
     *
     * @return the value of wxorder.mchid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getMchid() {
        return mchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.mchid
     *
     * @param mchid the value for wxorder.mchid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setMchid(String mchid) {
        this.mchid = mchid == null ? null : mchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.sign
     *
     * @return the value of wxorder.sign
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.sign
     *
     * @param sign the value for wxorder.sign
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.noncestr
     *
     * @return the value of wxorder.noncestr
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getNoncestr() {
        return noncestr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.noncestr
     *
     * @param noncestr the value for wxorder.noncestr
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setNoncestr(String noncestr) {
        this.noncestr = noncestr == null ? null : noncestr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.goodstag
     *
     * @return the value of wxorder.goodstag
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getGoodstag() {
        return goodstag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.goodstag
     *
     * @param goodstag the value for wxorder.goodstag
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setGoodstag(String goodstag) {
        this.goodstag = goodstag == null ? null : goodstag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.accountid
     *
     * @return the value of wxorder.accountid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.accountid
     *
     * @param accountid the value for wxorder.accountid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.prepayid
     *
     * @return the value of wxorder.prepayid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public Integer getPrepayid() {
        return prepayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.prepayid
     *
     * @param prepayid the value for wxorder.prepayid
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setPrepayid(Integer prepayid) {
        this.prepayid = prepayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.goods
     *
     * @return the value of wxorder.goods
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public String getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.goods
     *
     * @param goods the value for wxorder.goods
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setGoods(String goods) {
        this.goods = goods == null ? null : goods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.crdate
     *
     * @return the value of wxorder.crdate
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.crdate
     *
     * @param crdate the value for wxorder.crdate
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.status
     *
     * @return the value of wxorder.status
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.status
     *
     * @param status the value for wxorder.status
     *
     * @mbggenerated Thu Jun 11 18:00:36 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}