package cn.hd.ws.dao;

import cn.hd.ws.dao.Wxorder;
import cn.hd.ws.dao.WxorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int countByExample(WxorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int deleteByExample(WxorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int insert(Wxorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int insertSelective(Wxorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    List<Wxorder> selectByExample(WxorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    Wxorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") Wxorder record, @Param("example") WxorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int updateByExample(@Param("record") Wxorder record, @Param("example") WxorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int updateByPrimaryKeySelective(Wxorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated Tue Jul 14 17:34:07 CST 2015
     */
    int updateByPrimaryKey(Wxorder record);
}